### ISSUE TITLE
Allow sending encrypted data to server

### ISSUE THREAD

**Issue by hcsmatti** [lime-company/powerauth-cmd-tool#11]
For our activation process we need to be able to send encrypted credentials to server.

**Comment by petrdvorak** [comment]
To make this issue description more clear, we need to have a new command-line tool command `encrypt` that takes:

- Standard configuration properties (pamk.json file, pa_status.json file, etc.)
- Data file with request content
- Absolute URL to endpoint that receives encrypted payload

This command should take the request file data as payload, encrypt it via end-to-end encryption, send the encrypted payload to server endpoint specified by the URL, receive encrypted response, decrypt and print the original response.

**Comment by romanstrobl** [comment]
Thanks for the description, I will start working on this.

**Comment by romanstrobl** [comment]
Minor clarifications: 
* `pa_status.json` file will not be used in the encrypt step, the encryption needs to work before an activation is created (sending encrypted data to intermediate server can be a part of the activation process)
* The end-to-end encryption is non-personalized - we will use the same encryptor as encryptor used in CreateActivationStep.
